config/routes.rb
ShootTheShit::Application.routes.draw do
  devise_for :users
  resources :users
  resources :pages
  resources :musings
  resources :comments, :only => [:create]
  resources :votes
  resources :chat

  match '/musings_list/popular',  to: 'musings_list#popular'
  match '/musings_list/local',    to: 'musings_list#local'
  match '/musings_list/recent',   to: 'musings_list#recent'

  root :to => "musings_list#popular"

  devise_for :users do
    get 'logout' => 'devise/sessions#destroy'
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
   attr_accessible :content, :user_id, :musing_id
  # attr_accessible :content
   validates :content, :presence => true
   belongs_to :musing
   belongs_to :user
end

app/models/musing.rb
class Musing < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :title, :content, :voteCount, :longitude, :latitude, :city
  # has_many :comments
  # has_many :votes
  belongs_to :user
  has_many :comments
  has_many :votes

  validates :title, :presence => true
  validates :content, :presence => true


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  validates_uniqueness_of :username

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :name, :bio, :fb_profile, :twitter_profile

  validates :username, presence: true, length: { maximum: 50 }


  has_many :musings
  has_many :comments
  has_many :votes

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :user_id, :musing_id, :up
  belongs_to :musing
  belongs_to :user
  validates :user_id, :uniqueness => { :scope => :musing_id }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  def set_timezone
    Time.zone =  'Pacific Time (US & Canada)'
  end
  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  before_filter :authenticate_user!
  before_filter :set_globals

  def set_globals
    @secondary_navbar = true
    @highlight_chat = true
    @chat_title = true
  end

  def index
    @global_navbar = true
  end

  def show
    @chat_view = true
    @back_button = true
    @back_link = "/chat"
    @show_chat_input = true
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :set_timezone

  def show
  end

  def new
  end

  def create
    @comment = current_user.comments.create(params[:comment])
    if @comment.save
      flash[:notice] = "Comment successfully created."
    else
      flash[:notice] = "Could not create a blank comment."
    end

    redirect_to :back
  end

end

app/controllers/musings_controller.rb
class MusingsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :set_timezone

  before_filter :set_globals
  def set_globals
    @secondary_navbar = true
  end

  def show
    @musing = Musing.find(params[:id])
    @comment = Comment.new
    @back_button = true
    @back_link = '/'
    @title = @musing.title
    @show_musing_title = true
    @add_comment = true
  end

  def new
    @musing = Musing.new
    @secondary_navbar = true
    @back_button = true
    @new_musing_title = true
    @back_link = '/'
  end

  def create
    @back_button = true
    @back_link = '/'
    @musing = current_user.musings.create(params[:musing])


    respond_to do |format|
      if @musing.save
        format.html { redirect_to @musing, :notice => 'Musing was successfully created.' }
        format.json { render :json => @musing }
      else
        format.html { render :action => "new" }
        format.json { render :json => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

end

app/controllers/musings_list_controller.rb
class MusingsListController < ApplicationController
  before_filter :authenticate_user!
  before_filter :set_timezone
  before_filter :set_globals
  def set_globals
    @secondary_navbar = true
    @pillbox_sorter = true
    @highlight_musings = true
    @global_navbar = true
  end

  def recent
    @sort = "recent"
    @musings = Musing.order("created_at DESC")
  end

  def popular
    @sort = "popular"
    @musings = Musing.where(:created_at => (Time.now - 7.day)..Time.now).order("votecount DESC")
  end

  def local
    radius = 10;
    @sort = "local"
    @locationName = params[:locationName]
    @locationLongitude = params[:locationLongitude].to_f
    @locationLatitude = params[:locationLatitude].to_f
    @musings = Musing.where(:longitude => (@locationLongitude - radius)..(@locationLongitude + radius), :latitude => (@locationLatitude - radius)..(@locationLatitude + radius)).order("created_at DESC")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :set_globals

  def set_globals
    @secondary_navbar = true
    @global_navbar = true
    @user_title = true
  end

  def show
    @user = User.find(params[:id])
    if @user == current_user
    	@highlight_profile = true
    else
    	@back_button = true
    end
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :authenticate_user!

  def index
    create
  end

  def show
  end

  def new
  end

  ##BUG: when revote, need to increment by 2 not 1
  def create
    @oldVote = current_user.votes.where(:musing_id => params[:vote][:musing_id]).first
    @musing = Musing.where(:id => params[:vote][:musing_id]).first


    if @oldVote
      @oldVoteUp = @oldVote.up
      @newVoteUp = params[:vote][:up]
      if (@oldVoteUp == true)
        if (@newVoteUp != false)
          @musing.votecount -=2
          @oldVote.update_attributes(:up => false)
          @oldVote.save
          @musing.save
        end
      else
        if (@newVoteUp != true)
          @musing.votecount +=2
          @oldVote.update_attributes(:up => true)
          @oldVote.save;
          @musing.save
        end
      end
    else
      @vote = current_user.votes.create(params[:vote])
      if @vote.up
        @musing.votecount += 1
      else
        @musing.votecount -= 1
      end
    end
    @musing.save
    redirect_to :back
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/musings_helper.rb
module MusingsHelper
end

app/helpers/musings_list_helper.rb
module MusingsListHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/chat/index.html.erb
<p>Start chatting with a random shitter using the button below!</p>
<br>
<%= link_to "Start Chatting", '/chat/chat', :class => "button-block chat-button" %>

app/views/chat/show.html.erb
<div id="conversation">
    <div id="searchBox">
        <p id="searchingText">Searching...</p>
        <div id="floatingBarsG">
            <div class="blockG" id="rotateG_01"></div>
            <div class="blockG" id="rotateG_02"></div>
            <div class="blockG" id="rotateG_03"></div>
            <div class="blockG" id="rotateG_04"></div>
            <div class="blockG" id="rotateG_05"></div>
            <div class="blockG" id="rotateG_06"></div>
            <div class="blockG" id="rotateG_07"></div>
            <div class="blockG" id="rotateG_08"></div>
        </div>
    </div>
</div>

<!-- backend-y stuff below -->
<div pub-key="pub-11b5d2e6-425f-477a-ad20-9890c72cb283" sub-key="sub-17443687-2a05-11e2-8a20-7d0e10df7bde" ssl="off" origin="pubsub.pubnub.com" id="pubnub"></div>
<script src="http://cdn.pubnub.com/pubnub-3.3.min.js"></script>
<script>
// global data
// uuid from http://stackoverflow.com/questions/105034/how-to-create-a-guid-uuid-in-javascript
var uuid = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
    var r = Math.random()*16|0, v = c == 'x' ? r : (r&0x3|0x8);
    return v.toString(16);
});
var chatting = false;
var testing = false;
var theirUuid = "";

var waitingForAckFrom = "";
var stopSearchingTimeout = null;

function startChat(theirId) {
    // prepare globals
    chatting = true;
    theirUuid = theirId;
    $("#conversation").html("");

    PUBNUB.subscribe({ // subscribe to your own channel
        channel    : uuid,
        restore    : false,

        callback   : function(message) {
            // check for control messages first
            if (message.indexOf("LEAVE") === 0) { // they bailed
                alert("User disconnected from chat.");
                endChat();
                document.location.reload(true);
            }
            else {
                $("#conversation").append("<div class='message theirMessage'>" + message + "</div>");
            }
        }
    });

    PUBNUB.subscribe({ // subscribe to their channel
        channel    : theirUuid,
        restore    : false,

        disconnect : function() {
            endChat();
        },
        callback   : function() {

        }
    });
}

function sendChat(msg) {
    if (msg.length > 0) {
        if (!testing) {
            PUBNUB.publish({
                channel : theirUuid,
                message : msg
            });
        }
        $("#conversation").append("<div class='message myMessage'>" + msg + "</div>");
        if (testing) {
            $("#conversation").append("<div class='message theirMessage'>" + msg + "</div>");
        }
    }  
}

function endChat() {
    // notify other user that you are leaving
    PUBNUB.publish({
        channel : theirUuid,
        message : "LEAVE " + uuid
    });

    // leave
    PUBNUB.unsubscribe({ channel : theirUuid });
    PUBNUB.unsubscribe({ channel : uuid });
}

function searchForChat() {
    PUBNUB.subscribe({
        channel    : "connections",
        restore    : false,

        callback   : function(message) {
            message = message.split(" ");
            if (message[0] == "STARTCHAT" && message[1] == uuid) { // someone is starting a chat with us
                PUBNUB.publish({
                    channel : "connections",
                    message : "ACK " + message[2] + " " + uuid // ack them and start the chat
                });
                stopSearching();
                startChat(message[2]);
            }
            else if (message[0] == "ONLINE" && waitingForAckFrom == "" && message[1] !== uuid) {
                // let's try to start a chat with them
                PUBNUB.publish({
                    channel : "connections",
                    message : "STARTCHAT " + message[1] + " " + uuid
                });
                waitingForAckFrom = message[1];
            }
            else if (message[0] == "ACK" && message[1] == uuid && message[2] == waitingForAckFrom) {
                // they acknowledged us starting a chat with them. Go!
                stopSearching();
                startChat(message[2]);
            }
        },
        connect    : function() {
            PUBNUB.publish({
                channel : "connections",
                message : "ONLINE " + uuid
            });
        }
    })

    // stop searching after 45 seconds
    stopSearchingTimeout = window.setTimeout(function() {
        stopSearching();
        alert("Unable to connect to user (not enough users are online). Trying again...");
        document.location.reload(true);
    }, 45000);
}

function stopSearching() {
    clearTimeout(stopSearchingTimeout);
    PUBNUB.unsubscribe({ channel : 'connections' });
}

// event handlers
$("#sendChat").bind("click", function(e) {
    message = $("#chatMessage").val();
    $("#chatMessage").val("");
    sendChat(message);
    e.preventDefault();
});
$("a.new_person_button").bind("click", function() {
    if (chatting) {
        endChat();
    }
});

// let's go!
searchForChat();

// for testing purposes only, in user testing after 5 seconds connect to echo bot
window.setTimeout(function() {
    if (!chatting) {
        stopSearching();
        startChat("asdf");
        testing = true;
        alert("Began chat with test user because nobody is online");
    }
}, 10000);
</script>

app/views/layouts/_add_comment.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <nav class="bar-tab fieldSubmit">
      <%= f.text_field :content, :class => "navInputField", :placeholder => "Add a comment" %>
      <%= f.hidden_field :musing_id, :value => @musing.id %>

    <div class="actions comment_actions">
      <%= link_to_function "Submit", "document.getElementById('new_comment').submit();", :class => "navSubmitButton post_comment" %>
    </div>
  </nav>
<% end %>

app/views/layouts/_chat_input.html.erb
<nav class="comment_input bar-tab">
    <div class="comment_input_wrapper">
        <input type="text" id="chatMessage" placeholder="Type in a message"></input>
    </div>
    <div class="chat_actions">
      <a id="sendChat" href="#" class="post navSubmitButton">Send</a>
    </div>
</nav>

app/views/layouts/_global_navbar.html.erb
<nav class="bar-tab">
  <ul class="tab-inner">
    <li class="tab-item <%= "active" if @highlight_musings %>">
      <a href="<%= url_for(root_path) %>">
        <img class="tab-icon" src="">
        <div class="tab-label">Musings</div>
      </a>
    </li>
    <li class="tab-item <%= "active" if @highlight_chat %>">
      <a href="<%= url_for('/chat') %>">
        <img class="tab-icon" src="">
        <div class="tab-label">Chat</div>
      </a>
    </li>
    <li class="tab-item <%= "active" if @highlight_profile %>">
      <a href="<%= url_for(current_user) %>">
        <img class="tab-icon" src="">
        <div class="tab-label">Profile</div>
      </a>
    </li>
  </ul>
</nav>

app/views/layouts/_list_musings.html.erb
<%#= link_to "Add a new musing", new_musing_path, :class => "newMusingButton" %>
<ul id="musings">
  <% if !@musings.blank? %>
    <% @musings.each do |musing| %>
      <li class="musing">
        <div class="voteCount">
          <%= musing.votecount %>
        </div>
        <div class="title">
          <%= link_to musing.title, musing %>
        </div>
        <div class="byline">
          <span class="musingAuthor">
             by <%= u = User.find(musing.user_id); link_to u.username, u  %>
          </span>
          <span class="musingDate">
            on <%= l musing.created_at, :format => "%d/%m/%y at %I:%M %p" %>
          </span>
          <% if musing.city? %>
            <span class="musingCity">
              near <%= musing.city %>
            </span>
          <% end %>
        </div>
        <div class="musingContent">
          <%= truncate(musing.content, :length => 180, :separator => ' ') %>
        </div>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/layouts/_pillbox_sorter.html.erb
<% if @pillbox_sorter  %>
    <script type="text/javascript">
      function passLocationToController(object) {
            var url = "<%= url_for(:action => 'local', :controller => 'musings_list') %>";
            url += "?locationName=" + "Stanford";//object.name;
            url += "&locationLatitude=" + "37.41960923882351";//object.latitude;
            url += "&locationLongitude=" + "-122.1668823388235";//object.longitude;
            window.location = url;
      }
    </script>
    <ul class="segmented-controller">
      <li class="<%= ((@sort == "popular") ? "active" : nil) %>">
        <%= link_to "Popular", url_for(:action => 'popular', :controller => 'musings_list') %>
      </li>
      <li class="<%= ((@sort == "recent") ? "active" : nil) %>">
        <%= link_to "Recent", url_for(:action => 'recent', :controller => 'musings_list') %>
      </li>
      <li class="<%= ((@sort == "local") ? "active" : nil) %>">
        <%= link_to_function "Local", "callbackSwitch = PASS_LOCATION_TO_CONTROLLER; initLocation();" %>
      </li>
    </ul>
<% end %>

app/views/layouts/_secondary_navbar.html.erb
<!-- Not in js assets because requires erb to generat link -->
 <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
 <!-- This is not really save, change so it sends by post -->

<header class="bar-title">
  <% if @back_button %>
    <% if @back_link %>
      <%= link_to "<", @back_link, :class => "button backButton" %>
    <% else %>
      <a href="#" onclick="goBack(event);" class="button backButton"><</a>
    <% end %>
  <% end %>
  <!-- <h1 class="title">Title</h1> -->
  <% if @pillbox_sorter  %>
    <h1 class="title">Musings</h1>
    <%= link_to "+", new_musing_path, :class => "button newMusingLink" %>
  <% end %>
  <% if @chat_title %>
    <h1 class="title">Shit Chat</h1>
    <% if @chat_view %>
      <%= link_to "New", '/chat/chat', :class => "new_person_button" %>
    <% end %>
  <% end %>
  <% if @user_title %>
    <h1 class="title"><%= @user.username %></h1>
  <% end %>
  <% if @new_musing_title %>
    <h1 class="title">Create New Musing</h1>
  <% end %>
  <% if @show_musing_title %>
    <h1 class="title"><%= @title %></h1>
  <% end %>
  <% if @edit_profile %>
    <h1 class="title">Edit your profile</h1>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShootTheShit</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="apple-touch-icon" href="/assets/icon.png" />
  <link rel="apple-touch-startup-image" href="/assets/background.png" />
  <!-- FIXME: Move these things into a real place outside of this file -->
<!--   <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
  <meta name="apple-mobile-web-app-status-bar-style" content="black"> -->

<meta name="apple-touch-fullscreen" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">

<!-- <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script type="text/javascript" src="http://www.google.com/jsapi"></script>
 -->
  <script type="text/javascript">

  </script>
</head>
<body>

  <% if @secondary_navbar %>
    <%= render '/layouts/secondary_navbar' %>
  <% end %>
  <% if @global_navbar %>
    <%= render '/layouts/global_navbar' %>
  <% end %>
  <% if @add_comment %>
    <%= render 'layouts/add_comment' %>
  <% end %>
  <% if @show_chat_input %>
    <%= render 'layouts/chat_input' %>
  <% end %>
  <div class="content">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>



</body>
</html>

app/views/musings/create.html.erb
<h2>This is the page to create a new musing.</h2>

app/views/musings/new.html.erb
<!-- Google location api for get location on musing -->
<!-- Not entirely sure whether its better to have in application.js -->

<%= form_for(@musing) do |f| %>
  <% if @musing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@musing.errors.count, "error") %> prohibited this musing from being saved:</h2>

      <ul>
      <% @musing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title, :placeholder => "Title" %>
  </div>
  <div class="field">
    <%= f.text_area :content, :rows => "5", :placeholder => "Type you musing here..." %>
  </div>

  <div class="field">
    <%= f.hidden_field :latitude %>
  </div>
  <div class="field">
    <%= f.hidden_field :longitude %>
  </div>
  <div class="field">
    <%= f.text_field :city, :placeholder => "City" %>
  </div>
  <div class="actions">
    <%= link_to_function "Add location", "callbackSwitch = SET_LOCATION_DEF; initLocation();", {:class => "button-block green", :id => "locationButton"} %>
    <%= link_to_function "Add new musing", "document.getElementById('new_musing').submit();", :class => "button-block green" %>
  </div>
<% end %>

app/views/musings/show.html.erb
<div class="showMusing">
  <div class="voteCount"><%= @musing.votecount %></div>
  <div class="musingAuthor">
     by <%= u = User.find(@musing.user_id); link_to u.username, u  %>
  </div>
  <div class="subline">
    <span class="musingDate">
      on <%= l @musing.created_at, :format => "%d/%m/%y at %I:%M %p" %>
    </span>
    <% if @musing.city? %>
      <span class="musingCity">
        near <%= @musing.city %>
      </span>
    <% end %>
  </div>
  <div class="musingContent">
    <%= @musing.content %>
  </div>
  <div class="votes">
    <% if current_user && current_user.votes.where(:musing_id => @musing.id, :up => true).present? %>
    <div class="votePlaceholder sick">
      Sick
    </div>
    <% else %>
      <%= link_to "Sick", votes_path(:vote => {:musing_id => @musing.id, :up => true}), { :class => "button voteButton sick", :method => 'post'} %>
    <% end %>

    <% if current_user && current_user.votes.where(:musing_id => @musing.id, :up => false).present? %>
    <div class="votePlaceholder shit">
      Shit
    </div>
    <% else %>
      <%= link_to "Shit", votes_path(:vote => {:musing_id => @musing.id, :up => false}), { :class => "button voteButton shit", :method => 'post'} %>
    <% end %>
  </div>
</div>
<div class="comments">
  <h2 class="commentsTitle">Comments</h2>
    <% @musing.comments.each do |comment| %>
      <div class="comment">
          <span class="commentUsername">
            <%= u = User.find(comment.user_id); link_to u.username, u %>: 
          </span>
          <%= comment.content %>
      </div>
    <% end %>
</div>

app/views/musings_list/local.html.erb
<%= render '/layouts/pillbox_sorter' %>
<h2>Musings near <%= @locationName %></h2>
<%= render '/layouts/list_musings' %>

app/views/musings_list/popular.html.erb
<%= render '/layouts/pillbox_sorter' %>
<%= render '/layouts/list_musings' %>

app/views/musings_list/recent.html.erb
<%= render '/layouts/pillbox_sorter' %>
<%= render '/layouts/list_musings' %>

app/views/pages/_list_all_musings.html.erb
<%= link_to "Add a new musing", new_musing_path, :class => "newMusingButton" %>
<ul id="musings">
  <% if !@musings.blank? %>
    <% @musings.each do |musing| %>
      <li class="musing">
        <div class="title">
          <%= link_to musing.title, musing %>
        </div>
        <div class="byline">
          <span class="musingDate">
            <%= l musing.created_at, :format => "%d/%m/%y at %I:%M %p" %>
          </span>
          <span class="musingAuthor">
             by <%= u = User.find(musing.user_id); link_to u.username, u  %>
          </span>
        </div>
        <div class="musingContent">
          <%= truncate(musing.content, :length => 180, :separator => ' ') %>
        </div>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/users/show.html.erb
<div class="publicProfile">
  <% if @user.name? %>
    <div class="name">
      Name: <%= @user.name %>
    </div>
  <% end %>
  <% if @user.username? %>
    <div class="userName">
      Username: <%= @user.username %>
    </div>
  <% end %>
  <% if @user.fb_profile? %>
    <div class="fbProfileLink">
      Facebook Profile: <%= link_to "Facebook Profile", @user.fb_profile %>
    </div>
  <% end %>
  <% if @user.twitter_profile? %>
    <div class="twitterProfileLink">
      Twitter Profile: <%= link_to "Twitter Profile", @user.twitter_profile %>
    </div>
  <% end %>
  <% if @user.bio? %>
    <div class="bi">
      Bio: <%= @user.bio %>
    </div>
  <% end %>
  <% if (@user == current_user) %>
    <%= link_to "Edit Profile", edit_user_registration_path, :class => "button-block grey" %>
    <%#= link_to 'Sign Out1', destroy_user_session_path, :method => 'delete' %>
    <%= link_to "Logout", logout_path, :class => "button-block grey" %>
  <% end %>
</div>